### ISSUE TITLE
打开后报错

### ISSUE THREAD

**Issue by bofeiw** [sunkwei/mxnet_tetris#1]
无法运行，望解决

Mac terminal 输入python3 game.py train，
报错：
Traceback (most recent call last):
  File "game.py", line 692, in <module>
    game.step()
  File "game.py", line 243, in step
    if not self.create_new_shape():
  File "game.py", line 222, in create_new_shape
    if self.data_[p[0]][p[1]] != 0:
TypeError: list indices must be integers or slices, not float

**Comment by sunkwei** [comment]
使用 python3 game.py online 吧

**Comment by bofeiw** [comment]
不行，同样报错
FEI:mxnet_tetris-master fei$ python3 game.py online
Traceback (most recent call last):
  File "game.py", line 692, in <module>
    game.step()
  File "game.py", line 243, in step
    if not self.create_new_shape():
  File "game.py", line 222, in create_new_shape
    if self.data_[p[0]][p[1]] != 0:
TypeError: list indices must be integers or slices, not float

**Comment by sunkwei** [comment]
恩，这个是python3下的bug，已经修复，fetch/merge 一下
